# What is Databrary?

Databrary is...

## What is my role?

### As an Institution

Institutions are responsible overseeing the researchers at their institution in their use of Databrary and its resources.

### As a Researcher

I must have human subjects training (e.g. [CITI](https://about.citiprogram.org/) training), be employed at an institution that has an ethics or [Institutional Review Board](https://www.fda.gov/regulatory-information/search-fda-guidance-documents/institutional-review-boards-frequently-asked-questions), and be able to conduct independent research at my institution.

I would like to reuse or upload data to Databrary. I need to read and sign a Databary Access agreement and its' Annexes (I, II, III) before I may be authorized.

I can sponsor lab staff/students that are working on my projects to see my data or others data on Databrary.


### As a Student or Staff

I can only use non-public content on Databrary AFTER my supervisor has been granted authorization by their institution. This may take longer than I anticipate, so I will ask for authorization as early as possible.

## Why should I use Databrary?

Videos are expensive and time consuming to collect. It is likely that another researcher could answer their research questions by utilizing my videos.

Many granting agencies require that data are shared. Databrary is a way to share video data and link the published papers and other repositories (e.g. GitHub) to it.