# Edit a Volume

## Overview {-}

### Edit Volume Overview

### Edit Citation

update the citation of my project
    - setting sharing level
    - Manage Access
    - add cited authors vs. non cited researchers

## Manage Access {-}

### to the Volume {-}

Volume level:
    - "private"
    - "share overview only"
    - "share entire volume"

### for my Collaborators {-}

Authorized investigators can add affiliates and give them different levels of permission:
    - view and access only public data
    - view and access only shared data
    - read only
    - read/write
    - investigator (read/write/share)
    
Appearance order of investigators for citation purposes 

Add yourself last!

## Set up Spreadsheet {-}

### Spreadsheet preview

## Add Data {-}

- Select appropriate [release level](https://www.databrary.org/resources/guide/investigators/release/release-levels.html) for session in Databrary.

### Enter Metadata {-}

### New Session or Materials Folder to a volume {-} 

### Add Files to an existing session/materials folder {-}

## Share a volume {-}

### Directly with other Authorized Databrary Users {-}

 
    - with my collaborators/lab members that work on the data set
      - Grant Affiliate Access to individuals are under my supervision
      - Grant Collaborator Access - ONLY to an investigator already sponsored by an institution or another authorized investigator  
### All Authorized Databrary Users {-}
