# Databrary Definitions

**Access Agreement**: The Databrary Access Agreement between an
Authorized Investigator and his or her Institution and New York
University (NYU) on behalf of Databrary.

**Affiliate**: A person who conducts research under an Authorized
Investigator's sponsorship and supervision and who has been granted
access to Databrary by the Authorized Investigator. In most cases,
Affiliates are students or research staff and are not eligible for
Authorized Investigator status.

**Authorized Investigator**: A person who has permission from an
Institution to conduct independent research and who has received
authorization from an Institution and from Databrary to access
Databrary.

**Authorized Organizational Representative (AOR)**: A person granted
authority by an Institution to sign the Databrary Access Agreement on
behalf of the Institution and thereby bind the Institution to the terms
of the Databary Access Agreement.

**Institution**: An academic, not-for-profit, research, government, or
health entity whose employees or students conduct scientific research or
educational activities.