# Participant Info

## Bill of Rights (https://github.com/databrary/policies/blob/master/bill-of-rights.md) {-}
As a person who shares information with Databrary, you have the right to:

- Be free of pressure from anyone else when deciding if you wish to share information
- Make up your mind about sharing information without being rushed
- Have the decision to share information with Databrary be separate from the decision to participate in research
- Be told what information is being shared with Databrary
- Be told if there will be no direct benefit to you
- Ask questions about Databrary at any time before, during or after you participate in a study or agree to share information
- Refuse to share data without penalty
- Ask to have your data removed from sharing on Databrary, without any penalty
- Receive a copy of your Databrary release form for you to keep
- Be assured that your identity will be kept in confidence by Databrary and its authorized researchers.

If I have any questions or concerns I can contact Databrary staff by email at contact@databrary.org. I can also ask the staff from the study I participated in for help.