# Reusing data



## How do I download data on Databrary for reuse {-}

Re-using shared data on Databrary
  - Download
    - entire volume (be careful, these can be quite large.)
      - Download as .zip
    - a single session
      - Download vs. Download Original 
 
  
## Ethics of Reusing Data {-}

Authorized Investigators must secure Institutional approvals prior to conducting research with data shared on Databrary. In the U.S. context, conducting secondary analysis on shared video data may not qualify as human subjects research because there is no direct contact with research participants. Still, a research project involving video data reuse may require ethics board or IRB review and approval because the data are identifiable.


## How to cite reused data {-}

Shared Data should have a citation on the volume profile page under the 'How to cite' heading it takes the format of:

LastName, FirstInitial. (year volume was added). Title of Volume. *Databrary*. Retrieved Month DD, YYYY from [link to assigned doi].

Find an example of a public volume [here](https://nyu.databrary.org/volume/686)

Admin, D., Gilmore, R.O., Seisler, A.R. & Soska, K. (2018). Databrary & Datavyu Help Videos. *Databrary*. Retrieved February 7, 2023 from http://doi.org/10.17910/B7.686. 

## How to cite Databrary {-}

Databrary. (2014). Databrary.org. https://nyu.databrary.org/

Datavyu Team (2014). Datavyu: A Video Coding Tool. Databrary Project, New York University. URL http://datavyu.org.

