project:
  type: book
  output-dir: "docs"
  
book:
  title: "Databrary Guide"
  cover-image: img/databrary-nav-sm.jpg
  subtitle: "How to use Databrary to share research data"
  author: ["Rick Gilmore", "Andrea Seisler", "Melody Xu", "Yinghe Liu"]
  date: last-modified
  chapters:
    - index.qmd
    - introduction.qmd
    - part: "For Institutions"
      chapters:
        - background.qmd
        - ethics.qmd
    - part: "For Authorized Investigators"
      chapters:
        - determine-status.qmd
        - requesting-access.qmd
        - onboarding.qmd
        - managing-people.qmd
        - create-new-volume.qmd
        - edit-existing-volume.qmd
        - reusing-data.qmd
        - data-sharing.qmd
        - best-practices.qmd
        - grants.qmd
        - faq.qmd
    - part: "For Affiliates"
      chapters: 
        - determine-status.qmd
        - Chapters-for-Affiliates/requesting-access-affiliates.qmd
        - Chapters-for-Affiliates/onboarding-affiliates.qmd
        - create-new-volume.qmd
        - edit-existing-volume.qmd
        - reusing-data.qmd
        - data-sharing.qmd
        - best-practices.qmd
        - grants.qmd
        - faq.qmd
    - references.qmd
  appendices:
    - access_agreement.qmd
    - participant-info.qmd
    - privacy-policy.qmd
    - terms.qmd
  repo-url: https://github.com/databrary/guide

bibliography: [packages.bib, references.bib]
bibliography-style: apa

format:
  html:
    theme: cosmo
    css: style.css
    iframe: true
  epub:
    cover-image: img/databrary-nav-sm.jpg

output: 
  number_sections: true