project:
  type: book
  output-dir: "docs"
  
book:
  title: "Databrary Guide"
  cover-image: img/databrary-nav-sm.jpg
  subtitle: "How to use Databrary to share research data"
  author: ["Rick Gilmore", "Andrea Seisler", "Melody Xu", "Yinghe Liu"]
  date: last-modified
  chapters:
    - index.qmd # This is the file that contains the front matter, found in the root of the repository
    - Chapters-for-Backgrounds/introduction.qmd 
    - Chapters-for-Backgrounds/ethics.qmd
    - Chapters-for-Backgrounds/determine-status.qmd

    - part: Chapters-for-Affiliates/Affiliates-Intro.qmd 
      chapters: 
        - Chapters-for-Affiliates/requesting-access-affiliates.qmd
        - Chapters-for-Affiliates/onboarding-affiliates.qmd
        - Chapters-for-Affiliates/creating-new-volume-affiliates.qmd
        - Chapters-for-Affiliates/edit-existing-volume-affiliates.qmd
        - Chapters-for-Affiliates/reusing-data-affiliates.qmd
        
    - Chapters-for-References/faq.qmd 
    - Chapters-for-References/references.qmd 
    - Chapters-for-References/definitions.qmd
  appendices:
    - Chapters-for-Appendices/access_agreement.qmd
    - Chapters-for-Appendices/participant_info.qmd
    - Chapters-for-Appendices/privacy_policy.qmd
    - Chapters-for-Appendices/terms.qmd
    - Chapters-for-Appendices/grants.qmd

  repo-url: https://github.com/databrary/guide

bibliography: [packages.bib, references.bib]
bibliography-style: apa

format:
  html:
    theme: cosmo
    css: style.css 
    number_sections: false
  epub:
    cover-image: img/databrary-nav-sm.jpg

number-depth: 0