project:
  type: book
  output-dir: "docs"
  
book:
  title: "Databrary Guide"
  cover-image: img/databrary-nav-sm.jpg
  subtitle: "How to use Databrary to share research data"
  author: "Rick Gilmore, Andrea Seisler, Melody Xu, and Yinghe Liu"
  date: last-modified
  chapters:
    - index.qmd
    - introduction.qmd
    - ethics.qmd
    - grants.qmd
    - requesting-access.qmd
    - onboarding.qmd
    - managing-people.qmd
    - create-new-volume.qmd
    - edit-existing-volume.qmd
    - reusing-data.qmd
    - data-sharing.qmd
    - best-practices.qmd
    - faq.qmd
    - references.qmd
  appendices:
    - access_agreement.qmd
    - participant-info.qmd

bibliography: [packages.bib, references.bib]

format:
  html:
    theme: cosmo
  epub:
    cover-image: img/databrary-nav-sm.jpg
