# Ethics

As a restricted access data repository specialized for storing and sharing sensitive and identifiable research data, especially video, Databrary has developed an interlocking web of ethical principles and policies.

## Principles {-}

Databrary strives to uphold the highest research ethics while maximizing open and secure access to research data. We achieve this through multiple means:

- Requiring that researchers fulfill all institutional requirements, including ethics board or Institutional Review Board (IRB) review if needed, in order to use Databrary materials.
- Providing researchers with [template language](https://databrary.org/support/irb/irb-application.html) that may be used to apply for and secure ethics board approval.
- Requiring researchers to ask research participants for their permission to share data and providing [template language](https://databrary.org/support/irb/release-template.html) to guide the process. We also provide a [template](https://databrary.org/support/irb/staff-release.html) for securing sharing permission from research staff that are recorded.
- Providing a sample participant data sharing release [script](https://databrary.org/support/irb/script.html) and example [videos](https://databrary.org/support/irb/examples.html) of the data sharing release process.
- [Sample Email](https://databrary.org/support/irb/email.html) requesting data sharing release when it is not possible to obtain permission at the time of the visit
- Developing consistent [terminology and visual icons](https://databrary.org/support/irb/release-levels.html) for documenting sharing release levels.
- Providing [guidance](https://databrary.org/support/irb/grandfathering-data.html) about when and how data collected previously might be stored and shared on Databrary.

## Ethics/IRB Review {- #EthicsIRB}

Below is boilerplate language prepared by Databrary that researchers can use to help draft applications to their institutional review board (IRB). This document is intended to help researchers who plan to store and share video data in Databrary prepare IRB materials for approval.

Researchers should confirm institution/agency/directorate/program-specific application requirements before submission.

Please contact us at contact@databrary.org for further assistance.

### Secondary Reuse {- #reuse}
This project will conduct secondary analyses of participant data obtained from Databrary, an online platform for the storage, sharing, and re-use of video and other research data. Participants' consent for study participation and release of data were obtained by the original researcher under the oversight of their institutional review board. Because there is no direct contact with participants as a part of this project, the level of additional risk to participants is low.

### Primary data collection {- #primary}

Data will be handled by the team of researchers approved on the IRB protocols of all Principal Investigators and Co-Investigators. Data are linked to participants by subject ID. However, video data are potentially identifiable because participants' faces are visible and their names may be heard. With participant consent, study data will be stored on Databrary, a secure web-based video library housed at NYU, allowing permission-based access to coders from all labs comprising the project team. At the end of each lab visit, caregivers will be asked whether they are comfortable: 1) storing their videos and children's birthdates and other metadata on Databrary, and 2) sharing their data with authorized researchers outside of this protocol who are members of the academic research and clinical communities authorized to access Databrary. If caregivers agree to video sharing, the videos will be made available to authorized researchers as outlined below. If caregivers do not agree, their videos will be accessible only by researchers on the project protocol and not shared with the larger community. The policies for sharing videos and other potentially identifiable data on Databrary have been carefully developed and monitored with the advice of the legal counsel, grants/contracts office, and IRBs of both New York University and The Pennsylvania State University. Currently, more than 360 institutions in the U.S. and around the world have formally approved the Databrary Access Agreement to enable video sharing and reuse. Parents also will be told that they can share portions of data or ask for particular sessions not to be shared while sharing other sessions.

### Policies for Databrary access and data sharing {- #sharing}

Sensitive or identifiable data shared with Databrary will only be viewable to and downloadable by authorized users who have been granted secure access by Databrary's administrators. Select data may be made available to the public, but only as determined by the researcher and on the basis of participant permission. Only researchers with Principal Investigator status from institutions with Institutional Review Boards or similar review entities, and researchers affiliated with Principal Investigators and under their supervision, are authorized for access.

Authorized users are required to sign a user access agreement that specifies that they will: (1) be responsible for maintaining the confidentiality of the data; (2) abide by ethical principles for treatment of human subjects as mandated by their local Institutional Review Boards; (3) agree not use the data for commercial purposes; and (4) treat data in Databrary with the same high standards of care that they would treat data collected in their own laboratories.

Only videos and other identifiable data that have been permissioned for sharing by all the depicted individuals in each recording are made available to the community of authorized Databrary users. In consultation with ethics board officials at New York University and the Pennsylvania State University, Databrary has developed template Sharing Release forms that contributors can add to their IRB protocol. These forms allow researchers to ask participants for permission to share their data.

Federal policies do not require re-consenting of minor participants when they reach the age of majority, if re-consenting is impractical or otherwise increases risks to participants (e.g., by requiring researchers to maintain links between identifiable information and collected data for extended time periods).

### Policies and provisions for reuse and redistribution {- #redistribution}

Access to videos and metadata will be available for educational and research purposes, subject to participant consent. Such access will be provided using the Databrary web-based application. Materials generated under the project will be disseminated in accordance with the policies of [GRANT-GIVING ORGANIZATION] and participating institutions. Publication of data shall occur during the project, if appropriate, or at the end of the project, consistent with normal scientific practices.

### Archiving and preservation of research data {- #archiving}

Data in Databrary will be preserved indefinitely in a secure data storage facility at New York University (NYU); the facility is managed by the university's Information Technology Services department. Central IT staff handle storage, network, and backup systems. NYU does routine tape backups that are stored off site and performs regular file fixity checks to monitor the integrity of stored assets. Federal regulations do not require that data be destroyed after a particular time period if they are stored indefinitely in a recognized repository.

### Data Security {- #datasecurity}
Data and metadata stored in Databrary are subject to the security policies and best practices implemented by NYU. For more information about these policies and services, please visit NYU ITS Computer & Network Security at https://www.nyu.edu/life/information-technology/cybersecurity.html.

## Permission to share {-}

### Sharing release template forms for download {- #sharingtemplate} 

Data sharing release templates for [Participants](file/DB-participant-release-template_2022-03-22.docx)
and [Lab Staff](file/staff-release.pdf).  

### Sample Script for requesting permission to share {- #sample-share-script}

Now that you have finished this session, there's one more thing we want to ask you. The data that researchers collect from babies and families are incredibly valuable for helping scientists to understand how children develop.

So we wanted to ask if you are comfortable with allowing us to share the data we collected from this session with other researchers just like the professor who runs this lab/project. The data would be shared in a secure, online library, it's not available to the public-- only researchers that are authorized by their University would be able to access the information in the library.

This permission form also asks whether you would allow other professors/ researchers like Dr. [PI’s Name] to show short bits of the videos to students or researchers for educational and scientific purposes. These data will not be used or shown for commercial purposes.

### Videos {-}

Example videos of requesting permission to share participant data on Databrary: <https://databrary.org/support/irb/examples.html>

## Sharing release levels {- #release-levels}

**Insert picture of sharing release levels here: https://databrary.org/support/irb/release-levels.html**

## Sharing data collected without a Databrary-specific release {-}

Does your consent form permit you to show or reuse recordings for educational and scientific purposes?

If you already use a video/audio or photo release form and want to find out whether you can share with Databrary, follow the following steps.

### Seek formal permission from your IRB {-}

If your release permits you to show recordings in educational or scientific settings, you may apply for formal permission from your IRB to share these recordings with Databrary. 

Please note: Databrary intends to store Data indefinitely
Some IRBs encourage researchers to include promises to destroy Data, especially recordings, after some fixed time period in order to limit risk to participants. Data destruction is antithetical to data sharing, and Databrary's Template Release language seeks explicit permission to share data indefinitely. NIH and NSF do not require data destruction clauses. Researchers who wish to store Data on Databrary should remove data destruction clauses from their informed consent documents for new Data and seek IRB guidance about whether archival Data can be shared.

### Determine what [sharing permission level](https://databrary.org/support/irb/release-levels.html) applies {-}

Authorized Users Release: Your current release mean that recordings can be shared __only__ for research use by other Databrary Investigators
Learning Audiences: Clips from those recordings be shown in educational and scientific contexts

### Share data with Databrary {-}

You may [create a new volume](#newvol) yourself or contact Databrary for help in doing so.

## Grants {-}

Many users want to know how to incorporate data sharing using Databrary in funding proposals to agencies like the U.S. National Science Foundation or National Institutes of Health.

Researchers should confirm funding agency, directorate, or program-specific resource sharing plans or data management plan requirements.

### Data Management Plan Template {-}

Below is boilerplate language prepared by Databrary that researchers can use to help draft data management or resource sharing plans. This document is intended to help researchers who plan to store and share video data in Databrary prepare grant materials for submission. The material here is particularly suited to NSF application requirements, but similar language can be adapted for NIH grants as well as private foundations. Please contact us at contact@databrary.org for further assistance.

Researchers should confirm institution/agency/directorate/program-specific resource sharing plan or data management plan requirements.

### Data Formats {-}

Databrary transcodes all deposited video data into standard and HTML5-compatible formats, currently H.264+AAC as MP4. It stores the original video file along with the transformed, web accessible video file. Databrary stores other data in their original formats (e.g., .doc, .docx, .xls, .xlsx, .txt, .csv, .pdf, .jpg, .png). As standards for preferred video file formats change over time, Databrary will perform file format migrations to those preferred formats.

### Metadata {-}

Databrary takes and stores metadata related to a full dataset (e.g., title, authors, related publication, description of study, keywords or tags, associated URLs), individual study sessions (e.g. metadata related to participants, study groups and conditions, location, language, and session date and tasks), and video files (e.g., title, duration, tags) related to a dataset. Metadata is added through a user-friendly web interface where auto-completion, suggested terms, and integration with third party services (e.g., CrossRef) guide users through its creation. Metadata may be accessed through the web interface, via API, or downloaded as a comma separated values (CSV) file.

### Documentation {-}

Data owners can upload and store on Databrary any number of related documents that assist other researchers in understanding their data (e.g. study protocol, coding manuals, output from video coding software, and procedural videos). These documents can be associated with the dataset as a whole, or with individual sessions within the dataset.

### Policies for access and sharing {-}

Data will be stored with, and shared through, Databrary. Researchers are asked to avoid the inclusion of extraneous personally identifiable information (PII) in videos uploaded to Databrary. However, given the nature of video, it might still be possible to identify individuals based on first names, facial features, or details of the environment. Because of this, sensitive or identifiable data shared with Databrary will only be viewable and downloadable to authorized users who have been granted secure access by Databrary’s administrators. Select data may be made available to the public, but only as determined by the researcher and on the basis of participant permission. Only researchers with Principal Investigator status from institutions with Institutional Review Boards or similar review entities, or researchers affiliated with Principal Investigators, will be authorized for access.

Authorized users will be required to sign a user agreement that specifies that they will: (1) be responsible for maintaining the confidentiality of the data; (2) abide by ethical principles for treatment of human subjects as mandated by their local Institutional Review Boards; (3) agree not use the data for commercial purposes; and (4) treat data in Databrary with the same high standards of care that they would treat data collected in their own laboratories.

Although Databrary will store complete study data, only videos and other identifiable data that have been permissioned for sharing by all the depicted individuals in each recording will be made available to the community of authorized users. Databrary has developed template Sharing Release forms that contributors can add to their IRB protocol. These forms allow researchers to ask participants for permission to share their data.

Data owners can choose to share their data at any point, either as they collect their data, or only once data collection has completed.

### Policies and provisions for reuse and redistribution {-}

Access to videos and metadata will be available for educational and research purposes, subject to participant consent. Such access will be provided using the Databrary web-based application. Materials generated under the project will be disseminated in accordance with the policies of [GRANT-GIVING ORGANIZATION] and participating institutions. Publication of data shall occur during the project, if appropriate, or at the end of the project, consistent with normal scientific practices.

### Plans for archiving and preservation {-}

Data in Databrary will be preserved indefinitely in a secure data storage facility at New York University (NYU). The facility is managed by the university’s Information Technology Services department. Central IT staff handle storage, network, and backup systems. NYU does routine tape backups that are stored off site and performs regular file fixity checks to monitor the integrity of stored assets.

### Versioning of stored assets {-}

Files uploaded to Databrary are assigned a unique identifier and have metadata associating them to files that are uploaded to replace them. Though only the latest version of a file is exposed to Databrary site users. Files, once uploaded, are never deleted.

### Data Security {-}

Data and metadata stored in Databrary are subject to the security policies and best practices implemented by NYU. For more information about these policies and services, please visit NYU ITS Computer & Network Security at <https://www.nyu.edu/life/information-technology/cybersecurity.html>.

## Internal Data Use Agreement Information {-}

- This Agreement is different from a traditional DUA because there is no obligation for authorized investigators to use or to contribute data. Once our researchers are planning to share data from their lab or repurpose shared data, they would seek proper IRB approval for those activities.  

- The Data on Databrary Contains PII  

- HIPAA data is not stored on Databrary  

- Does the Consent Form used to collect the data permit its disclosure or has it been authorized by the relevant IRB(s)? Yes  

- All data on Databrary were collected and shared under the supervision of an IRB.  

- What is the purpose of the Data Exchange? The purpose of Databrary is to share research data between researchers to foster data reuse.  

- Describe the data being exchanged: The data are primarily video data of behavioral research in addition to stimuli that have been used for research studies.  

### Databrary’s Contact Information:

<p>Databrary<br/>
4 Washington Place<br/>
Room 409<br/>
New York, NY 10003<br/>
tel: (212) 998-9058<br/>
contact@databrary.org</p><br/>
