# Principal Investigators {.unnumbered}

## Eligibility {-}

Databrary policies and your home institution determine whether you are eligible to be granted access to Databrary as an **Authorized Investigator**.
To be eligible as a Databrary Authorized Investigator, you must meet these criteria: 

- I conduct independent, unsupervised, research at my institution;
- I submit funding proposals as lead investigator;
- I have Principal Investigator (PI) status or hold a tenure-track faculty position at my institution;
- My institution maintains or uses an ethics board to review and approve research involving human subjects (or non-human animals where relevant); 
- I have current training that addresses research ethics with human subjects (e.g. [CITI](https://about.citiprogram.org/) training);
- I would like to reuse or upload data to Databrary.
- I sponsor and supervise lab staff and students who work on my projects or on collaborative projects, and I  have authority to supervise their access to data that I share or others have shared on Databrary.

## Seeking Authorization {-}

If these criteria apply to you, you must [register](https://nyu.databrary.org/user/register) on Databrary, request authorization from your institution, and complete our Databrary Authorization form.

If you would like to check if your institution is already part of the Databrary community, you can search through the [full list of institutions](https://databrary.org/search?tab=2) on Databrary.

If your institution is not yet a part of the Databrary community, please read our [Databrary Community](../for-institutions/join-the-databrary-community.qmd) page.

### 1. Register on Databrary

Registration involves creating an account using your institutional email, setting a password, and confirming your account.

::: {.callout-note}

An institutional email address is the email address granted to you by the institution or university in which you are employed and does **not** end in `.com`.

:::

### 2. Request Authorization

Requesting authorization involves securing approval and signatures from both you and the Authorized Organizational Representative (AOR) at your institution on the [Databrary Access Agreement (DAA)](../appendices/access_agreement.qmd) and its Annexes.

If you know who at your institution reviews, approves, and signs data access agreements or other contracts, that is your AOR who will need to sign the DAA. If you don't know who that person at your institution is, Databrary staff will help identify the right person. Databrary will work with you and your institution to secure signatures on the DAA. 

Please email [contact@databrary.org](contact@databrary.org) if you need assistance in finding your AOR. 

### 3. Databrary Authorization Request Form

Lastly, please fill out the [Databrary Authorization Request form](https://airtable.com/appcrDDgPR8DGVGsS/shrtBwpYGFbvylwCV). Once your responses are submitted, the Databrary team will contact you with next steps.
