# Getting Authorized {.unnumbered #sec-getting-started}

Databrary follows a restricted access data sharing model due to the sensitive identifiable data we host. All Databrary users **must** be authorized by either their institution or an active Databrary authorized researcher in order to access identifiable data on Databrary. 

Please refer to our [Data Ethics](../ethics/ethics.qmd) page for more information about Databrary's ethical principles.

Any person may browse and view Databrary's public materials consistent with the [Terms & Conditions of Use](/appendices/terms.qmd). You may only download public materials if you are logged in to Databrary.

::: {.callout-note}

If you do not complete the authorization process, but you have a registered account on Databrary, you will only be able to access **public** data on Databrary that are de-identified data or have been permissioned to be shared publicly.

:::

## Why Do I Need to Get Authorized? {.unnumbered}

Databrary strives to uphold the highest standards of research ethics while maximizing open and secure access to research data. We achieve this through multiple means, one of them being requiring that researchers fulfill all institutional requirements, including research ethics board or Institutional Review Board (IRB) review if needed, in order to use Databrary materials.

If you represent an **institution**, see [this section](/for-institutions/for-institutions.qmd) for information about how researchers gain access to Databrary via a formal process of institutional authorization.

If you are a **researcher**, see [this section](authorized-researchers.qmd) about how to start the authorization process with your institution.

If you are a **research staff member, postdoc, graduate or undergraduate student**, see [this section](sponsored-researchers.qmd) for information about how to gain access to restricted data via your research supervisor. 
