# Who and why? {.unnumbered #sec-who-why}

This section describes who can access Databrary and why they might want to.

As mentioned in the last chapter, many of Databrary's holdings are restricted to researchers who have secured authorization from their home institution or are affiliated with (or sponsored by) a researcher who has authorization.

This extra step ensures that sensitive and identifiable data are shared only with people who have formal authorization to access it, who have research ethics training, and who are affiliated with institutions that have agreed to monitor data use.
Databrary calls these people [*Authorized Investigators*](../more-information/definitions.qmd#authorized-investigator) and [*Affiliates*](../more-information/definitions.qmd#affiliate).
*Authorized Investigators* may request access to restricted data and may share data with *Affiliates* and other *Authorized Investigators*, and sometimes with the general public.
*Affiliates* may request access to restricted data through an *Authorized Investigators* but may not share data with other users.

All parties, even members of the public, are responsible for the appropriate use of Databrary and the materials stored there.
Responsibilities that apply to everyone are set out in the [Databrary Terms and Conditions of Use](https://databrary.org/about/policies/terms.html). 
For *Authorized Investigators* and *Affiliates*, there are additional responsibilities.
*Authorized Investigators* and *Affiliates* must ensure that their use of Databrary complies with the terms of the [agreement](../appendices/access_agreement.qmd) their institution has signed to permit access to Databrary. 

## What's my status {.unnumbered}

One of the first things a new Databrary user must determine is what status they can have, *Authorized Investigator* or *Affiliate*.
Authorized Investigators have more privileges and responsibilities because of their more permanent and official status with an institution that grants a person authorization through the Databrary Access Agreement. 
Here are some factors to consider about whether you qualify as an *Authorized Investigator* or as an *Affiliate*:

I am eligible to become an *Authorized Investigator* if:

- I conduct independent, unsupervised, research at my institution;

- I submit funding proposals as lead investigator;

- I have Principal Investigator (PI) status or a tenure-track faculty position at my institution;

- My institution maintains or uses an ethics board to review and approve research involving human subjects (or animals where relevant); 

- I have current training that addresses research ethics with human subject (e.g. [CITI](https://about.citiprogram.org/) training);

- I would like to reuse or upload data to Databrary. I need to read and sign a Databrary Access agreement and its' Annexes (I, II, III) before I may be authorized.

- I sponsor and supervise lab staff and students who work on my projects and have authority to supervise their access to data I share or or others have shared on Databrary.

I am eligible to become an *Affiliate* if:

-   I conduct research under the supervision of an *Authorized Investigator*'s sponsorship or someone who is eligible to become an *Authorized Investigator*; 
-   I am a student, research staff, or post-doctoral researcher.
-   I have current training that addresses research ethics with human subjects (e.g.[CITI](https://about.citiprogram.org/) training.

::: {.callout-important}

If you are eligible for *Affiliate* status, your supervisor or research sponsor must [register](https://databrary.org/user/register) as an *Authorized Investigator* <u>BEFORE</u> you may request affiliate access from them.
Communicate with your sponsor or supervisor about your request.

:::

## Why should I use Databrary? {-}

Sharing information is what curious and inventive minds have been doing for millenia.
It's how we advance as a community.
Data repositories and libraries provide permanent homes for research findings and raw data.
Sharing research data is a vital component of the research process just like publishing papers and books, giving talks, and teaching classes.

On a more practical level, videos are expensive and time consuming to collect. 
It's possible, maybe even likely depending on what your videos recorded that another researcher could answer their research questions with videos you've already collected.

Finally, many granting agencies that fund research require that research data be shared. 
So, by sharing data on Databrary, you'll not only accelerate discovery, but you'll also meet an important obligation to research sponsors and often taxpapers who fund them.
