# Databrary for institutions

## What is Databrary? {-}

Databrary is a restricted access data library specialized for storing,
streaming, and sharing of video and audio recordings. Databrary's
mission is to support the sharing of video and audio recordings and
related data collected as part of research in the social, behavioral,
educational, and neural sciences.

The responsibility for protecting research data and research
participants is shared among Authorized Investigators and their
Affiliates, Institutions, and Databrary.

Databrary has a multi-pronged approach to fostering the sharing of video
and related data while upholding ethical research principles. Access is
restricted to Authorized Investigators whose access must be approved by
their Institution. Institutions must provide ethics oversight of
Authorized Investigators through a research ethics board or
Institutional Review Board (IRB) with standards equivalent to that
required to secure Federalwide Assurance (FWA) status from the U.S.
Government (see:
<https://www.hhs.gov/ohrp/register-irbs-and-obtain-fwas/index.html>).
Authorized Investigators who share data with others must secure
permission to share from research participants and record that
permission level for each file stored on Databrary. In turn, Authorized
Investigators who access Databrary and use data shared by other
Authorized Investigators must follow ethical research principles,
including respect for the sharing permissions granted by research
participants. Taken together, these features aim to protect the rights
of research participants while reducing barriers to sharing data.

## The Databrary Access Agreement permits data use and data contribution  {-}

Databrary restricts access to Authorized Investigators whose
Institutions sign a formal Databrary Access Agreement.

The Databrary Access Agreement combines provisions for data use and data
contribution. Unlike data use agreements that allow specific individuals
access to a particular dataset for a discrete research purpose, the
Databrary Access Agreement allows any Authorized Investigator to access
all shared datasets on Databrary and use the datasets for many different
Institutionally-approved purposes. In addition, the Databrary Access
Agreement permits Authorized Investigators to upload data and to share
it with other Authorized Investigators in accord with the sharing
permissions granted by participants and any required Institutional
approvals. Databrary believes that combining data use and data
contribution in a single agreement reduces barriers to data sharing,
meets emerging funder mandates to share research data, and accelerates
progress in research.

## Video's use cases extend beyond research  {-}

In addition to its many uses in research, video may be used for a
variety of pre-research and non-research uses, such as the documentation
of methodological details, the demonstration of computer-based tasks, or
the showing of video clips for teaching or scientific presentations.
Databrary encourages the storage and sharing of video for all of these
purposes, in a manner consistent with subject permissions and
institutional approvals.

## Institutions determine when research ethics board or IRB approval is necessary  {-}

Databrary does not require prior research ethics board or IRB approval
for an Authorized Investigator to be granted access to the system or to
use Databrary's shared resources for non-research, educational, or
pre-research uses. However, in signing the Databrary Access Agreement,
all Authorized Investigators promise to secure research ethics approval
whenever their use of Databrary requires it under the Institution's
policies.

Non-research, educational, or pre-research use cases may not require
research ethics board or IRB review and approval at every institution.
Institutions decide which use cases require research ethics board or IRB
review and approval.

## What data are shared  {-}

Databrary contains images, video, and audio recordings that may be
identifiable, data and metadata that are not typically sensitive, and
de-identified data. Exact birth dates may be stored for use in
calculating exact ages, but exact birth dates are only exposed to
Authorized Investigators or Affiliates given specific access to data.
Names, addresses, email addresses, financial information, government ID
numbers, detailed geographic location information, and other personally
identifiable data elements are **not** stored and shared on Databrary.

## Securing permission to share  {-}

In order to contribute and share identifiable data with Databrary,
Authorized Investigators must secure permission to store the recordings
on Databrary from research participants and any other people (e.g.,
research staff) who are recorded.

Databrary has developed a Sharing Release Template that informs people
depicted in recordings of the potential risks associated with sharing
video and other data on Databrary. The Sharing Release Template is one
of the resources that Databrary has made available to researchers. The
Sharing Release Template may be adapted for use at any Institution and
added to any research ethics or IRB protocol. However, an Institution
may require other release language in order to provide equivalent
protections.

Whether de-identified or pseudonymized data may be shared with Databrary
without seeking explicit permission from research participants depends
on the Authorized Investigator's Institution. Some ethics boards or
IRBs may allow de-identified or pseudonymized data to be shared without
the explicit permission of the research participant.

## Uploading data and assigning sharing permission levels  {-}

Authorized Investigators who upload data to Databrary must assign to
each file uploaded the level of data sharing granted by research
participants---from none to public access. The sharing level assigned to
each file by default is *Private*, meaning that no person other than the
Authorized Investigator who uploaded the file and any Affiliates granted
access by the Authorized Investigator, may view the file.

Not only are data files assigned a *Private* sharing level by default,
but all newly created datasets are initially made *Private*, accessible
only to an Authorized Investigator, any Affiliates the Authorized
Investigator selects, and any other individual Authorized Investigators
granted specific access to the dataset. An Authorized Investigator may
elect to create an overview of a dataset when it is created and make the
overview publicly available. The overview can serve as the public face
of the dataset while the dataset is being collected and analyzed. This
can be useful in documenting progress on a research grant to sponsors.
The dataset overview does not expose data unless the Authorized
Investigator chooses to do so.

## Sharing data  {-}

At a time when the Authorized Investigator chooses---e.g., when a paper
goes to press or a grant period ends---the Authorized Investigator may
choose to share the dataset with other Authorized Investigators on
Databrary. This makes the data contained in the dataset available to
other Authorized Investigators and possibly the public, but only in
accordance with the sharing levels selected by Authorized Investigators
and always subject to the permission granted by participants. That is,
individual data files marked *Private* remain accessible only to people
the Authorized Investigator specifically selects. Similarly, access to
datasets labeled *Private* remains solely under the control of the
Authorized Investigator.

## Databrary and GDPR  {-}

Authorized Investigators may collect personal data from research
participants who have rights under the General Data Protection
Regulation (GDPR). GDPR governs the collection of personal data in the
European Economic Area (EEA).

Databrary's servers are currently located in the United States, and
data stored on Databrary may be accessed, downloaded, and re-used by
Authorized Investigators and their Affiliates located outside of the
EEA. There are more than 500 Institutions across the globe that have
signed the Databrary Access Agreement. Databrary maintains a list of
Authorized Investigators who have access to shared research data at
<https://nyu.databrary.org/search?volume=false&f.party_authorization=4&f.party_is_institution=false>.

In seeking permission to collect data from research participants
governed by GDPR or similar provisions, Authorized Investigators should
communicate to research participants information about who may have
access to shared data on Databrary and where the data are stored.
Institutions and Authorized Investigators assume responsibility for
ensuring that research participants give sharing data permission that
satisfies the provisions of GDPR and for abiding by other provisions of
GDPR.

Databrary does not typically store information that links a person's
identity to specific files unless there is a separate agreement between
the Authorized Investigator, the Institution, and Databrary to store
this type of data. Therefore, if a research participant requests a copy
of data stored on Databrary or the modification or deletion of personal
data that is stored on Databrary, the Authorized Investigator or
Institution is responsible for responding to the request, not Databrary.
Also, Databrary cannot guarantee that data previously shared with other
Authorized Investigators via Databrary can be retrieved from all
Authorized Investigators who accessed a participant's personal data
prior to its modification or removal. Thus, Authorized Investigators
should communicate to research participants that there are limits to a
participant's right to modify or delete personal data that have already
been shared on Databrary. The Databrary Release Template contains
language for this purpose.

When accessing data shared by other Authorized Investigators,
Institutions and their Authorized Investigators assume responsibility
for ensuring that the sharing permission research participants have
given in other contexts outside of the EEA meet relevant GDPR
provisions.

## When Authorized Investigators leave an Institution  {-}

Authorized Investigators are expected to inform Databrary when they
leave an Institution. Institutions may also inform Databrary.

Access to non-public data shared with other Authorized Investigators
will be suspended when an Authorized Investigator leaves an Institution.
The suspension extends to an Authorized Investigators' Affiliates.
Authorized Investigators will continue to have password-protected access
to data they uploaded to Databrary once they leave an Institution. When
a new Institution grants authorization, Authorized Investigators will
regain access to non-public data shared by other Authorized
Investigators.

If an Authorized Investigator retires, is incapacitated due to illness,
or dies, the Institution should inform Databrary so that the Authorized
Investigator's account may be suspended. An Institution may choose to
designate a data steward for the Authorized Investigator's data and
authorize that person to manage access to the data. If the Institution
does not identify and authorize a data steward, Databrary staff will
serve that role. However, the Databrary staff serving as data steward
will not change the data sharing status of any specific dataset without
explicit written guidance from the Institution.

## Selecting Affiliates  {-}

If permitted by their Institution, an Authorized Investigator may grant
a person outside their Institution Affiliate status. Institutions may
establish policies governing the selection and management of Affiliates
by their Authorized Investigators.

If a person is eligible to be an Authorized Investigator at their home
Institution, that person must apply for access to Databrary through
their home Institution. Except in unusual circumstances, researchers
eligible to be Authorized Investigators at their home Institution should
not be granted access to Databrary as the Affiliate of another
Authorized Investigator either from the same Institution or a different
one. Databrary welcomes questions about these policies. Please email
<contact@databrary.org>.