# What is your status? {.unnumbered}

Since Databrary is designed by and for researchers, the first step is to determine what sort of status you have as a researcher.

## Overview {.unnumbered}

Databrary stores and shares data that are available to the public.
But most of the library's holdings are restricted to researchers who have secured authorization from their home institution or are affiliated with a researcher who has authorization.

This extra step ensures that sensitive and identifiable data are shared only with people who have formal authorization to access it, who have research ethics training, and who are affiliated with institutions that have agreed to monitor data use.

## Determining status {.unnumbered}

To determine what level of access you can request from Databrary, see the following.

I am eligible to become an **Authorized Investigator** if:  

+ I can conduct independent research;  
+ I can submit funding proposals as the lead investigator;  
+ I have Principal Investigator (PI) status or a tenure-track faculty position at my Institution;
+ My Institution maintains or uses an ethics board to review and approve research involving human subjects (or animals where relevant); AND
+ I have current training that addresses research ethics with human subject (or animals where relevant)    

I am eligible to become an **Affiliate** if: 

+ I conduct research under the supervision of a Principal Investigator an Authorized Investigator's sponsorship; AND
+ I am a student, research staff, or post-doctoral researcher  

If you are eligible for **Affiliate** status, your supervisor or research sponsor must register as an Authorized Investigator BEFORE you may request affiliate access from them.

## Rights and Obligations {.unnumbered}

Authorized Investigators and Affiliates are responsible for ensuring that their use of Databrary complies with the terms of their Institutional Agreement and with the Databrary Terms of Use. Additionally, they differ in the following ways:

+ Authorized Investigators may request access to restricted data and may share data with Affiliates and Authorized Investigators.
+ Affiliates may request access to restricted data but may not share data with other users.


