# Editing a Volume {.unnumbered}

## Overview {-}

### Edit Citation

Update the citation of my project
    - setting sharing level
    - Manage Access
    - add cited authors vs. non cited researchers

## Manage Access {-}

### to the Volume {-}

### for my Affiliates {-}

## Set up Spreadsheet {-}

## Add Data {-}

- Select appropriate [release level](https://www.databrary.org/resources/guide/investigators/release/release-levels.html) for session in Databrary.

### Enter Metadata {-}

### Creating a new Session or Materials folder {-}

Session folders are for participant sessions and materials folders are for thing related to the study such as surveys used, sample consent forms, and stimuli.

Session folders need to be added individually. Once the Participant ID is entered, the related metadata will be filled in. Then the rest of the session information will need to be added individually.

To add a new folder, go to the "Enter Data" tab on the left side of your screen. Scroll to the bottom of your volume. Select "add folder". Using the drop down menu, select the type of folder you wish to create ("sessions" or "materials"). 

### Add files to an existing Session or Materials folder {-}

To add files to an existing folder:
* Go to the "Enter Data" tab on the left side of your screen. 
* Find the name of the folder that you wish to add files to. 
* Select "add file", which will take you to the "Manage" page for the folder.
* You may upload files by either dragging and dropping them into the outlined space or by clicking and selecting the files you wish to upload.

Here is a video tutorial on how to [add a file on Databrary](https://nyu.databrary.org/volume/686/slot/27588/-?asset=122480)

### Remove or Replace files from an existing Session or Materials folder {-}

To remove a file:
* Navigate to the "Manage" page for the folder. 
* Click on the file that you wish to remove and select the "Remove file" button. Databrary will prompt you to confirm that you wish to remove the file. Please note that removed files cannot be recovered.

Here is a video tutorial on how to [remove a Databrary file](https://nyu.databrary.org/volume/686/slot/67044/-?asset=434274)

Alternatively, you can replace a file to upload a newer version of the same file while preserving the associated information. To replace a file:

* Click on the file that you wish to remove.
* Select the "Remove file" button. A window will pop up for you to select the file that you wish to replace the original file on Databrary with.

Here is a video tutorial on how to [replace a Databrary file](https://nyu.databrary.org/volume/686/slot/67045/-?asset=434276)

### Deleting a Sessions or Materials folder {-}

To delete a sessions of materials folder from your volume, you need to first remove all files and metadata associated with it. 

To remove files, see instructions above **insert link to section above**

Here is a video tutorial on how to [delete a Databrary folder](https://nyu.databrary.org/volume/686/slot/67043/-?asset=434284)

## Share a volume {-}

### Directly with other Authorized Databrary Users {-}

 
    - with my collaborators/lab members that work on the data set
      - Grant Affiliate Access to individuals are under my supervision
      - Grant Collaborator Access - ONLY to an investigator already sponsored by an institution or another authorized investigator  
### All Authorized Databrary Users {-}