# For Institutions {.unnumbered}

An institution is defined as an academic, not-for-profit, research, government, or health entity whose employees or students conduct scientific research or educational activities. Research and educational  [institutions](../more-information/definitions.qmd#institution) play a central role in the Databrary ecosystem.

This section describes some of those roles and responsibilities.
It is designed to answer the questions an official with grants and contracts or research ethics compliance responsibilities might ask.

Much of the material is adapted from the [Databrary Access Agreement and its three Annexes](../appendices/access_agreement.qmd).

If you are a researcher, research staff or trainee, you may skip this part.

::: {.callout-note}

There are several questions on the [FAQ](../more-information/faq.qmd) page that directly relate to institutional responsibilities, including:

[I qualify as an Authorized Organizational Representative (AOR). Can I sign as both authorized researcher and AOR?](../more-information/faq.qmd#i-qualify-as-an-authorized-organizational-representative-aor.-can-i-sign-as-both-authorized-investigator-and-aor)

[How much does Databrary cost?](../more-information/faq.qmd#how-much-does-databrary-cost)

:::

## What is Databrary? {-}

Databrary is a restricted access data library specialized for storing, streaming, and sharing of video and audio recordings. 
Databrary's mission is to support the sharing of video and audio recordings and related data collected as part of research in the social, behavioral, educational, and neural sciences.

The responsibility for protecting research data and research participants is shared among [authorized researchers](../more-information/definitions.qmd#authorized-investigator) and their [supervised researchers](../more-information/definitions.qmd#affiliate), institutions, and Databrary.

Databrary has a multi-pronged approach to fostering the sharing of video and related data while upholding ethical research principles. Access is restricted to authorized researchers whose access must be approved by their institution.

Institutions must provide ethics oversight of Authorized Investigators through a research ethics board or Institutional Review Board (IRB) with standards equivalent to that required to secure [Federalwide Assurance (FWA) status](https://www.hhs.gov/ohrp/register-irbs-and-obtain-fwas/index.html) from the U.S. Government.

Authorized researchers who share data with others must secure permission to share from research participants and record that permission level for each file stored on Databrary. 

In turn, authorized researchers who access Databrary and use data shared by other authorized researchers must follow ethical research principles, including respect for the sharing permissions granted by research participants. 

Taken together, these features aim to protect the rights of research participants while reducing barriers to sharing data.
