# Granting Authorization {.unnumbered}

## Researcher Seeking Authorization

In most cases, a researcher initiates a request for authorization when they [register](https://databrary.org/user/register) for access and create an account on Databrary.

A Databrary staff member will contact the institution to determine who should review and sign the Databrary Access Agreement (DAA) and its Annexes. Some institutions require the researcher to sign or initial the documents, alongside signatures from the Authorized Organizational Representative (AOR).

## Researcher Eligibility {-}

Access to restricted data on Databrary is limited to researchers who are formally authorized by their institutions via the [Databrary Access Agreement (DAA)](insert link to .qmd for DAA) and its Annexes. Only academic, research, government, or health entities are eligible to authorize researchers under the DAA. Institutions must also maintain or use an ethics or Institutional Review Board with U.S. equivalent standards that reviews and approves research involving human subjects (or non-human animals where relevant).

An official signature by an Authorized Organizational Representative (AOR) on the DAA constitutes formal institutional approval.

Once authorized by their institution, Databrary considers the researchers authorized researchers. While institutions decide whether to authorize a specific researcher, the following criteria typically apply:

- Eligible researchers conduct independent, unsupervised, research at the institution;
- Eligible researchers submit funding proposals as lead investigator;
- Eligible researchers have Principal Investigator (PI) status or hold a tenure-track faculty position at the institution;
- Eligible researchers have current training that addresses research ethics with human subject (e.g. [CITI](https://about.citiprogram.org/) training);
- Eligible researchers wish to download and/or reuse or upload data to Databrary.

Authorized researchers often supervise the research activities of research staff, postdocs, graduate students, and undergraduate students who are **not** eligible for access to Databrary as authorized researchers. Consistent with institutional policies, these individuals may be granted access to Databrary as a supervised researcher of a supervising authorized researcher.

## When an Authorized Researcher Transfers to a New Institution  {-}

It is the authorized researcher's and/or institution's responsibility to inform Databrary when the authorized researcher leaves the institution. It is the authorized researcher's and/or institution's responsibility to have a plan for data transfer and to share this plan with Databrary.

Access to non-public data shared with other authorized researchers will be suspended when an authorized researcher leaves an institution. The suspension extends to the authorized researcher's supervised researchers. Authorized researchers will continue to have password-protected access to data that they uploaded to Databrary once they leave an institution. When the new institution grants authorization, authorized researchers will regain access to non-public data shared by other authorized researchers.

::: {.callout-note}

If you are an authorized researcher who is sponsoring researchers on Databrary, please make sure your sponsored researchers will be authorized by another authorized researcher before you leave your institution.

:::

## When an Authorized Researcher Retires or Passes Away {-}

If an authorized researcher retires, is incapacitated due to illness, or passes away, it is the institution's responsibility to inform Databrary so that the authorized researcher's account may be suspended. 

An institution may choose to designate a data steward for the authorized researcher's data and authorize that person to manage the access to the data. If the institution does not identify and authorize a data steward, Databrary staff will serve that role. The Databrary staff serving as data steward will not change the data sharing status of any specific dataset without explicit written guidance from the institution.