# Grants

Many users want to know how to incorporate data sharing using Databrary in funding proposals to agencies like the U.S. National Science Foundation or National Institutes of Health.

Researchers should confirm funding agency, directorate, or program-specific resource sharing plans or data management plan requirements.

## Data Management Plan Template {-}

Below is boilerplate language prepared by Databrary that researchers can use to help draft data management or resource sharing plans. This document is intended to help researchers who plan to store and share video data in Databrary prepare grant materials for submission. The material here is particularly suited to NSF application requirements, but similar language can be adapted for NIH grants as well as private foundations. Please contact us at contact@databrary.org for further assistance.

Researchers should confirm institution/agency/directorate/program-specific resource sharing plan or data management plan requirements.

## Data Formats {-}
Databrary transcodes all deposited video data into standard and HTML5-compatible formats, currently H.264+AAC as MP4. It stores the original video file along with the transformed, web accessible video file. Databrary stores other data in their original formats (e.g., .doc, .docx, .xls, .xlsx, .txt, .csv, .pdf, .jpg, .png). As standards for preferred video file formats change over time, Databrary will perform file format migrations to those preferred formats.

## Metadata {-}
Databrary takes and stores metadata related to a full dataset (e.g., title, authors, related publication, description of study, keywords or tags, associated URLs), individual study sessions (e.g. metadata related to participants, study groups and conditions, location, language, and session date and tasks), and video files (e.g., title, duration, tags) related to a dataset. Metadata is added through a user-friendly web interface where auto-completion, suggested terms, and integration with third party services (e.g., CrossRef) guide users through its creation. Metadata may be accessed through the web interface, via API, or downloaded as a comma separated values (CSV) file.

## Documentation {-}
Data owners can upload and store on Databrary any number of related documents that assist other researchers in understanding their data (e.g. study protocol, coding manuals, output from video coding software, and procedural videos). These documents can be associated with the dataset as a whole, or with individual sessions within the dataset.

## Policies for access and sharing {-}
Data will be stored with, and shared through, Databrary. Researchers are asked to avoid the inclusion of extraneous personally identifiable information (PII) in videos uploaded to Databrary. However, given the nature of video, it might still be possible to identify individuals based on first names, facial features, or details of the environment. Because of this, sensitive or identifiable data shared with Databrary will only be viewable and downloadable to authorized users who have been granted secure access by Databrary’s administrators. Select data may be made available to the public, but only as determined by the researcher and on the basis of participant permission. Only researchers with Principal Investigator status from institutions with Institutional Review Boards or similar review entities, or researchers affiliated with Principal Investigators, will be authorized for access.

Authorized users will be required to sign a user agreement that specifies that they will: (1) be responsible for maintaining the confidentiality of the data; (2) abide by ethical principles for treatment of human subjects as mandated by their local Institutional Review Boards; (3) agree not use the data for commercial purposes; and (4) treat data in Databrary with the same high standards of care that they would treat data collected in their own laboratories.

Although Databrary will store complete study data, only videos and other identifiable data that have been permissioned for sharing by all the depicted individuals in each recording will be made available to the community of authorized users. Databrary has developed template Sharing Release forms that contributors can add to their IRB protocol. These forms allow researchers to ask participants for permission to share their data.

Data owners can choose to share their data at any point, either as they collect their data, or only once data collection has completed.

## Policies and provisions for reuse and redistribution {-}
Access to videos and metadata will be available for educational and research purposes, subject to participant consent. Such access will be provided using the Databrary web-based application. Materials generated under the project will be disseminated in accordance with the policies of [GRANT-GIVING ORGANIZATION] and participating institutions. Publication of data shall occur during the project, if appropriate, or at the end of the project, consistent with normal scientific practices.

## Plans for archiving and preservation {-}
Data in Databrary will be preserved indefinitely in a secure data storage facility at New York University (NYU). The facility is managed by the university’s Information Technology Services department. Central IT staff handle storage, network, and backup systems. NYU does routine tape backups that are stored off site and performs regular file fixity checks to monitor the integrity of stored assets.

## Versioning of stored assets {-}
Files uploaded to Databrary are assigned a unique identifier and have metadata associating them to files that are uploaded to replace them. Though only the latest version of a file is exposed to Databrary site users. Files, once uploaded, are never deleted.

## Data Security {-}
Data and metadata stored in Databrary are subject to the security policies and best practices implemented by NYU. For more information about these policies and services, please visit NYU ITS Computer & Network Security at https://www.nyu.edu/life/information-technology/cybersecurity.html.

## Internal Data Use Agreement Information {-}

This Agreement is different from a traditional DUA because there is no obligation for authorized investigators to use or to contribute data. Once our researchers are planning to share data from their lab or repurpose shared data, they would seek proper IRB approval for those activities.  

The Data on Databrary Contains PII  

HIPAA data is not stored on Databrary  

Does the Consent Form used to collect the data permit its disclosure or has it been authorized by the relevant IRB(s)? Yes  

All data on Databrary were collected and shared under the supervision of an IRB.  

What is the purpose of the Data Exchange? The purpose of Databrary is to share research data between researchers to foster data reuse.  

Describe the data being exchanged: The data are primarily video data of behavioral research in addition to stimuli that have been used for research studies.  

Databrary’s Contact Information:   
<p>Databrary<br/>
4 Washington Place<br/>
Room 409<br/>
New York, NY 10003<br/>
tel: (212) 998-9058<br/>
contact@databrary.org</p><br/>