---
bibliography: "include/bib/references.bib"
---

## Welcome {-}

This document describes the [Databrary.org](https://databrary.org) data library and how to use it effectively as a tool for safely and securely sharing identifiable research data including video and audio.

Databrary is used by a large and growing community of researchers across the globe, including some large scale research projects [@Soska2021-mh] run by Databrary's co-founders, Karen Adolph and Rick Gilmore, and their collaborators.

Databrary's founders believe that the widespread use and sharing of video can improve reproducibility and rigor of many different areas of research [@Adolph_KE_Gilmore_RO_Kennedy_JL2017-va; @Gilmore2017-wd].

## About the authors {-}

[Rick Gilmore](https://rick-gilmore.com) is Professor of Psychology at Penn State and is the Co-Founder and Co-Director of Databrary.

*Andrea Seisler* manages the Brain and Behavioral Dynamics Laboratory at Penn State and is the Authorizations and Support Specialist for Databrary.

*Kasey Soska* is Science Director for the [Play & Learning Across a Year](https://play-project.org) project.

*Melody Xu* was a User Support Specialist at Databrary until she began a Ph.D. program at Johns Hopkins University in August 2023.

*Yinghe Liu* was an undergraduate student in Psychology at Penn State.

*Anika Mahadevan* is an undergraduate student in Psychology and Biology at Penn State and will graduate in May 2027.

## References {-}

